#include <queue>
#include <vector>

using namespace std;
class Person
{
public:
	int get_rand_floor_generator(int floorCurrOn);//RANDOMIZES THE FLOOR BASED ON THE FLOOR THE USER IS CURRENTLY ON. FLOOR DEST ON ELEVATOR CLASS
	void set_rand_floor_generator(int userF);//SETTER FOR RAND FLOOR GEN. USED ELSEWHERE 
	void delay(int number_of_seconds);//SIMULATES A DELAY FOR THE ELEVATOR. 
	void queue_generator(int currFloor, int secDelay, queue<int> elevator_car);//GENERATES THE LINE FORMED OUTSIDE THE ELEVATOR. ASSUME THAT THE NUMBERS ARE THE FLOORS USER WANTS TO GO TO. ASSUME BUTTON IS PUSHED
	//WHEN THEY GET IN ELEVATOR. FLOOR DESTINATION DECIDED TO INDICATE POSITON WHEN ARRIVED.
	
	

private:
	//PEOPLE WAITING TO GET IN LINE FOR THE ELEVATOR. NOT THE PEOPLE IN THE ELEVATOR. LINE WILL NOT CONTAIN MORE THAN 20 PEOPLE, BEFORE PPL TAKE STAIRS
	queue<int> floor_1_queue;
	queue<int> floor_2_queue;
	queue<int> floor_3_queue;

	//VECTOR OF POSSIBLE FLOOR CHOICES NOT SURE IF I WILL USE THIS YET. SMALL ENOUGH POPULATION THAT I PREPOPULATED IT
	vector<int> floor1_options{ 2, 3 };
	vector<int> floor2_options{ 2, 3 };
	vector<int> floor3_options{ 1, 2 };

	//USER FLOOR DESTINATION. FLOOR IS RANDOMIZED.
	int userFloor;

};
//DOORS WILL TAKE NEGLIGIBLE AMOUNT OF TIME TO OPEN. WILL NOT INCLUDE IN THE TIME. TIME STAYING OPEN WILL MATTER FOR HOW MANY PEOPLE IN LINE
